site_name: Laravel SOAP Docs
site_description: 'Laravel SOAP Documentation'
site_author: 'Gregor Becker'
docs_dir: docs/v2/
repo_name: 'codedredd/laravel-soap'
repo_url: 'https://github.com/codedredd/laravel-soap'

# Copyright
copyright: Copyright &copy; 2020 - 2020 Gregor Becker

nav:
  - 'Get started': 'index.md'
  - Client:
      - Request: 'client/request.md'
      - Response: 'client/response.md'
      - authentication: 'client/authentication.md'
      - configuration: 'client/configuration.md'
  - Commands: 'commands.md'
  - Testing: 'testing.md'
theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'cyan'
    accent: 'deep orange'
markdown_extensions:
  - admonition
  - attr_list
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      extend_pygments_lang:
        - name: php-inline
          lang: php
          options:
            startinline: true
