site_name: Laravel SOAP Docs
site_description: 'Laravel SOAP Documentation'
site_author: 'Gregor Becker'
docs_dir: docs/
repo_name: 'codedredd/laravel-soap'
repo_url: 'https://github.com/codedredd/laravel-soap'
nav:
  - Home: index.md
theme:
  name: 'material'
